[package]
name = "tidal-rs"
version = "0.1.1"
edition = "2024"


[features]
console = []

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true


[dependencies]
tao = "0.34.5"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "net", "sync"] }
wry = "0.54.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0.100"
aes = "0.8.4"
cbc = "0.1.2"
ctr = "0.9.2"
base64 = "0.22.1"
tracing = "0.1.44"
reqwest = { version = "0.12", default-features = false, features = [
  "stream",
  "rustls-tls-native-roots",
] }
once_cell = "1.21.3"
futures-util = "0.3.31"
rodio = { version = "0.22", default-features = false, features = [
  "playback",
  "symphonia-flac",
  "symphonia-aac",
  "symphonia-isomp4",
] }
symphonia = { version = "0.5", features = ["flac", "aac", "isomp4"] }

[target.'cfg(target_os = "windows")'.dependencies]
wasapi = "0.22"
